### ISSUE TITLE
merlin setup broken since dune 2.8

### ISSUE THREAD

**Issue by fdopen** [fdopen/ppx_cstubs#5]
dune 2.8+ doesn't generate '.merlin' files any longer.
And merlin only calls ppx preprocessors for normal `*.ml` files, not for the `*.c.ml` files (see also #3 )

**Comment by fdopen** [comment]
I have asked about it [here](https://github.com/ocaml/merlin/issues/1262)

**Comment by sidkshatriya** [comment]
https://github.com/ocaml/merlin/issues/1262 has now been resolved due to merge of https://github.com/ocaml/dune/pull/4264 . Does this resolve this issue?

**Comment by fdopen** [comment]
Yes the originally issue is solved.
It seems to work now with merlin/emacs and on Visual Studio. However, I don't know how to test this in an automated way.
